# --------------------------------------------------------------
#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = logic-operators

# --------------------------------------------------------------
# Files to build

FILES_DSP  = \
	logic-operators.cpp \
	operators/operator.cpp

# --------------------------------------------------------------
# Do some magic

include ../../dpf/Makefile.plugins.mk

# --------------------------------------------------------------
# Enable only LV2

all: lv2_sep

# --------------------------------------------------------------
